### ISSUE TITLE
Available public dataset?

### ISSUE THREAD

**Issue by Guriido** [Jonas1312/swimming-pool-detection#1]
Hi Jonas!
As a replacement to the private dataset, one may use this dataset (in construction), have you heard about it?
https://geoservices.ign.fr/lidarhd
(English link from media: https://www.actuia.com/english/the-national-lidar-hd-programme-3d-mapping-of-the-entire-french-territory/)

Keep up with good projects!

**Comment by Jonas1312** [comment]
Hi!

Haven't heard about it but I know ign.fr, there's some interesting stuff: [https://remonterletemps.ign.fr/](https://remonterletemps.ign.fr/comparer/basic?x=2.161101&y=48.707895&z=18&layer1=ORTHOIMAGERY.ORTHOPHOTOS&layer2=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&mode=doubleMap)

Next project: caravane de gitan segmentation.
