### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by ThierryZen** [Jonas1312/swimming-pool-detection#2]
Hi Jonas,

I'm trying to execute this program for pool detection, but I am facing an issue that I could not resolve.
cf print screeen bellow
![image](https://user-images.githubusercontent.com/117768874/202474552-2f32bc9f-e055-4ce9-abab-c9ac74908c5f.png)

Any tips?
Many thanks
Best Regards
Thierry

**Comment by Jonas1312** [comment]
Hi,
Do you have the full exception traceback?

Thanks

**Comment by ThierryZen** [comment]
Many thanks for your reply,

Traceback is the following, I also attached it as a print screen:
(I've also copied Rodrigo as he's working with me on this topic)

TypeError                                 Traceback (most recent call last)
<ipython-input-15-2ee7fa2a79b1> in <module>
----> 1 pool_detector = PoolDetector(weights)

<ipython-input-11-43196efba1b8> in __init__(self, weights_path, device)
     14     def __init__(self, weights_path, device=None):
     15         self.device = torch.device('cpu') # (device) or
torch.device("cuda" if torch.cuda.is_available() else "cpu")
---> 16         self.model = self.load_model(weights_path)
     17
     18     def load_model(self, weights_path):

<ipython-input-11-43196efba1b8> in load_model(self, weights_path)
     17
     18     def load_model(self, weights_path):
---> 19         model = Model().to(self.device)
     20         model.load_state_dict(torch.load(weights_path))
     21         model.eval()

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in
_call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or
self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or
_global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

TypeError: forward() missing 1 required positional argument: 'x'

[image: image.png]


[image: Zentricx Logo]
[image: Instagram] <https://www.instagram.com/zentricx>
[image: Facebook] <https://www.facebook.com/zentricx>
[image: Linkedin] <https://www.linkedin.com/company/zentricx>
[image: Web] <https://www.zentricx.com/>
[image: Youtube] <https://www.youtube.com/channel/UCiBBd8JPHsvwuDVgJReKAYg>

[image: Grate][image: Cloud]
*Thierry Langlet*
| Data Engineer, Zentricx
 + 54 911 3934-7131
 + 54 911 4001-3122
 ***@***.***
*Linking People to** CX*



*CONFIDENCIALIDAD: Este mensaje es privado y los archivos adjuntos al mismo
son confidenciales y dirigidos exclusivamente a los destinatarios de los
mismos.Por favor, si Ud. no es uno de dichos destinatarios, sírvase
notificarnos este hecho y no copie o revele su contenido a
terceros.CONFIDENTIALITY: This message and any attached files are
confidential and intended only for the named recipients.If you are not one
of them, please, notify  us this  fact and do not disclose its contents to
another person or take any copies.*

**Comment by Jonas1312** [comment]
I can't reproduce the error under torch 1.13, Python3.10 and device="cpu"

**Comment by ThierryZen** [comment]
Dear Jonas, I am writing to you because I was finally able to run the model
we talked about a few days ago.

What I was missing in the model.load was the parameter

* map_location=torch.device('cpu')

I think it might be good to add it as a comment when one is going to use
CPU.

On the other hand I would like to ask you about the meaning of what appears
in the processed images:

- In this case, you can see that the model worked well, and I mark a pool
with 80% probability. Although in the lower left corner it marks with low
probability 35% something that is not a pool.
[image: Figure_1.png]
- But my doubts are in the two following cases: where you can see the red
boxes. What do they mean? Pileta with 0% probability?
- Second case, why didn't you mark in the second case the upper right pool,
if the heat map marks it clearly?

[image: Figure_2.png]
[image: Figure_3.png]
Thank you very much!


[image: Zentricx Logo]
[image: Instagram] <https://www.instagram.com/zentricx>
[image: Facebook] <https://www.facebook.com/zentricx>
[image: Linkedin] <https://www.linkedin.com/company/zentricx>
[image: Web] <https://www.zentricx.com/>
[image: Youtube] <https://www.youtube.com/channel/UCiBBd8JPHsvwuDVgJReKAYg>

[image: Grate][image: Cloud]
*Rodrigo Robert*
| Data Scientist, Zentricx
 + 54 9261 2525277
 + 54 911 4001-3122
 ***@***.*** ***@***.***>
*Linking People to** CX*



*CONFIDENCIALIDAD: Este mensaje es privado y los archivos adjuntos al mismo
son confidenciales y dirigidos exclusivamente a los destinatarios de los
mismos.Por favor, si Ud. no es uno de dichos destinatarios, sírvase
notificarnos este hecho y no copie o revele su contenido a
terceros.CONFIDENTIALITY: This message and any attached files are
confidential and intended only for the named recipients.If you are not one
of them, please, notify  us this  fact and do not disclose its contents to
another person or take any copies.*
